name: Package Application with PyInstaller
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Read version from version.txt
        id: get_version
        run: |
          echo "VERSION=$(cat src/version.txt)" >> $GITHUB_ENV

      - name: Package Application with PyInstaller
        run: |
          pyinstaller --noconfirm src/MultiRitoFixes.spec
        env:
          VERSION: ${{ env.VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-exe
          path: dist/